modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="vlwml"
version="Beta 1.1.0"
displayName="VillageWars Music Library"
credits="This mod was Created using MCreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Tsotciri"
description='''
This is the VillageWars Music Library an addon to the VLWDM (VillageWars Dedicated Mod)       
'''

[[dependencies.vlwml]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




