modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="vlwml"
version="1.1.0-beta"
displayName="VillageWars Music Library"
credits="This mod was Created using MCreator (https://mcreator.net)"
displayURL="https://youtube.com"
logoFile="logo.png"
authors="Tsotciri"
description='''
This is the VillageWars Music Library an addon to the VLWDM (VillageWars Dedicated Mod)       
'''

[[dependencies.vlwml]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




