/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.tsotciri.vldm;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class VlwdmModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public VlwdmModElements() {
		sounds.put(new ResourceLocation("vlwdm", "otherside"), new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "otherside")));
		sounds.put(new ResourceLocation("vlwdm", "shulk"), new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "shulk")));
		sounds.put(new ResourceLocation("vlwdm", "belupacito"), new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "belupacito")));
		sounds.put(new ResourceLocation("vlwdm", "pigstep_remix"), new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "pigstep_remix")));
		sounds.put(new ResourceLocation("vlwdm", "sus"), new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "sus")));
		sounds.put(new ResourceLocation("vlwdm", "hobbit.hobbit_ts"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "hobbit.hobbit_ts")));
		sounds.put(new ResourceLocation("vlwdm", "marvel.avengers_assemble"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "marvel.avengers_assemble")));
		sounds.put(new ResourceLocation("vlwdm", "marvel.marvel_ot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "marvel.marvel_ot")));
		sounds.put(new ResourceLocation("vlwdm", "memes.coffind_meme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "memes.coffind_meme")));
		sounds.put(new ResourceLocation("vlwdm", "memes.nyan"), new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "memes.nyan")));
		sounds.put(new ResourceLocation("vlwdm", "memes.rick_roll"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "memes.rick_roll")));
		sounds.put(new ResourceLocation("vlwdm", "memes.suniversal"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "memes.suniversal")));
		sounds.put(new ResourceLocation("vlwdm", "minigames.battle.music"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "minigames.battle.music")));
		sounds.put(new ResourceLocation("vlwdm", "minigames.tumble.music"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "minigames.tumble.music")));
		sounds.put(new ResourceLocation("vlwdm", "minigames.glide.music"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "minigames.glide.music")));
		sounds.put(new ResourceLocation("vlwdm", "songs.avengers_ts"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "songs.avengers_ts")));
		sounds.put(new ResourceLocation("vlwdm", "songs.universal_ot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "songs.universal_ot")));
		sounds.put(new ResourceLocation("vlwdm", "songs.coffind_full"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("vlwdm", "songs.coffind_full")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("vlwdm").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == VlwdmModElements.ModElement.class)
						elements.add((VlwdmModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(VlwdmModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new VlwdmModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		VlwdmMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final VlwdmModElements elements;
		protected final int sortid;
		public ModElement(VlwdmModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
